"use client";

import { useState } from "react";
import { ArrowRight, Banknote, Check, ChevronDown, Clipboard, ExternalLink, FileCheck2, FileText, Landmark, Mail, Scale, ShieldCheck, UserRound } from "lucide-react";
import Button from "@/components/ui/Button";
import GlassCard from "@/components/ui/GlassCard";
import SimpleModal from "./SimpleModal";
import { policeContact, simpleProcedureResources as links } from "@/data/simpleResources";

const external = { target: "_blank", rel: "noopener noreferrer" } as const;
const steps = [
  ["01", "Request repayment", "Set out the amount and identify the payments."],
  ["02", "Confirm by email", "Create another clear written record."],
  ["03", "Allow time to resolve", "Keep evidence while you await a response."],
  ["04", "Consider Simple Procedure", "Read the current official guidance."],
  ["05", "Follow the court process", "Follow instructions for your individual case."],
];
const template = `Dear [name],\n\nI am writing to confirm that I have sent you a formal request for repayment of £[amount], which I believe is owed to me in relation to [reason].\n\nPlease arrange repayment or contact me to resolve the matter.\n\nIf the matter cannot be resolved, I may consider raising proceedings to recover the outstanding sum.\n\nKind regards,\n\n[name]`;
const panel = "rounded-2xl border border-slate-200/70 bg-white/55 p-4 dark:border-white/10 dark:bg-white/5";

export default function SimpleGuide() {
  const [modal, setModal] = useState<"letter" | "email" | null>(null);
  const [email, setEmail] = useState(template);
  const [copied, setCopied] = useState(false);
  const copy = async () => { await navigator.clipboard.writeText(email); setCopied(true); window.setTimeout(() => setCopied(false), 1800); };
  return <>
    <section className="relative overflow-hidden rounded-[2rem] border border-white/60 bg-white/65 px-5 py-10 shadow-[0_24px_70px_rgba(15,23,42,.12)] backdrop-blur-xl dark:border-white/10 dark:bg-slate-900/50 sm:px-10 sm:py-14">
      <div aria-hidden className="absolute -right-16 -top-20 size-64 rounded-full bg-blue-400/15 blur-3xl"/><div className="relative max-w-3xl">
        <p className="mb-4 text-xs font-bold uppercase tracking-[.24em] text-blue-700 dark:text-blue-300">Owner resource</p>
        <div className="mb-5 grid size-14 place-items-center rounded-2xl bg-gradient-to-br from-blue-600 to-indigo-600 text-white shadow-lg"><Banknote/></div>
        <h1 className="text-3xl font-semibold tracking-tight text-slate-950 dark:text-white sm:text-5xl">Recovering Money from FIOR</h1>
        <p className="mt-5 text-lg leading-relaxed text-slate-700 dark:text-slate-200">Information for owners who believe they are personally owed money by FIOR Property Assets.</p>
        <p className="mt-3 max-w-2xl leading-relaxed text-slate-600 dark:text-slate-300">This guide explains a straightforward process for requesting repayment, keeping evidence and finding the official Scottish court resources if the matter cannot be resolved.</p>
      </div>
    </section>

    <aside className="mt-6 flex gap-4 rounded-2xl border border-blue-200/70 bg-blue-50/80 p-5 dark:border-blue-300/15 dark:bg-blue-400/10"><ShieldCheck className="mt-1 shrink-0 text-blue-700 dark:text-blue-300"/><div><h2 className="font-semibold text-slate-950 dark:text-white">Before you begin</h2><p className="mt-2 text-sm leading-relaxed text-slate-700 dark:text-slate-200">This page has been created to help James Square owners understand the process available to them for recovering money they believe is owed to them. It is for general information only and is not legal advice.</p><p className="mt-2 text-sm font-medium text-slate-800 dark:text-slate-100">Any claim is made by the individual owner and not by the James Square Owners Committee.</p></div></aside>

    <section className="py-14" aria-labelledby="process-title"><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-700 dark:text-blue-300">At a glance</p><h2 id="process-title" className="mt-2 text-3xl font-semibold text-slate-950 dark:text-white">How the process works</h2><p className="mt-3 max-w-2xl text-slate-600 dark:text-slate-300">Five straightforward stages, from requesting repayment to following the court process if the matter remains unresolved.</p>
      <ol className="relative mt-8 grid gap-3 before:absolute before:bottom-6 before:left-[1.45rem] before:top-6 before:w-px before:bg-blue-300 md:grid-cols-5 md:before:left-[10%] md:before:right-[10%] md:before:top-6 md:before:h-px md:before:w-auto">
        {steps.map(([number,title,desc], i)=><li key={number} className="relative pl-16 md:pl-0 md:pt-14"><a href={`#step-${i+1}`} className="group block rounded-2xl p-3 transition hover:bg-white/60 dark:hover:bg-white/5"><span className="absolute left-0 top-1 grid size-12 place-items-center rounded-full border-4 border-slate-50 bg-blue-600 text-sm font-bold text-white shadow md:left-1/2 md:-translate-x-1/2">{number}</span><strong className="block text-sm text-slate-900 dark:text-white">{title}</strong><span className="mt-1 block text-xs leading-relaxed text-slate-600 dark:text-slate-300">{desc}</span></a></li>)}
      </ol>
    </section>

    <div className="space-y-8">
      <Step id="step-1" number="01" title="Request repayment" intro="The first step is to clearly set out the amount you believe FIOR owes you and formally request repayment.">
        <p>Provide enough information for the payment to be identified.</p><div className={panel}><h3 className="font-semibold">Useful information to include</h3><ul className="mt-3 grid gap-2 text-sm sm:grid-cols-2">{["Full name","James Square property/address","Correspondence address, if different","Email address","Amount believed to be owed","What the payment or payments related to","Payment dates","Payment references where available","Brief information that helps identify the payment"].map(x=><li key={x} className="flex gap-2"><Check size={16} className="mt-0.5 shrink-0 text-blue-600"/>{x}</li>)}</ul></div><Button onClick={()=>setModal("letter")}><FileText size={18}/>Create repayment letter</Button><div className="flex gap-3 border-t border-slate-200 pt-5 dark:border-white/10"><FileCheck2 className="shrink-0 text-slate-500"/><p className="text-sm"><strong className="block text-slate-900 dark:text-white">Keep a copy</strong>Keep a copy of anything you send and, where possible, evidence showing when and how it was sent.</p></div>
      </Step>
      <Step id="step-2" number="02" title="Confirm it by email" intro="After sending your repayment request, it can be useful to also send an email confirming that a formal request has been made. This provides another written record of your request."><Button onClick={()=>setModal("email")}><Mail size={18}/>Create follow-up email</Button><p className="text-sm">Nothing is sent automatically. You can review and copy the suggested wording.</p></Step>
      <Step id="step-3" number="03" title="Allow time to resolve it" intro="Give FIOR a reasonable opportunity to respond and resolve the matter before deciding whether to take further action."><p>A repayment request may ask for a response or payment within 14 days. This page does not describe 14 days as a mandatory court deadline. Check the current official guidance before beginning any court process.</p><Evidence/><Outcomes/></Step>
      <Step id="step-4" number="04" title="Consider Simple Procedure" intro="If the matter has not been resolved, you may wish to consider making a claim using the Scottish Courts and Tribunals Service Simple Procedure."><p>Simple Procedure is generally used in Scotland for certain civil claims with a value of £5,000 or less.</p><p>A solicitor is not normally required to make a Simple Procedure claim, although an owner may choose to seek independent advice.</p><p className="font-semibold">The decision whether to make a claim belongs to the individual owner.</p><Resources/></Step>
      <Step id="step-5" number="05" title="Follow the court process" intro="If you decide to submit a claim, the Scottish Courts and Tribunals Service and the relevant court will provide information about what happens next."><p>Carefully read any correspondence you receive and follow the instructions and deadlines provided for your individual case. The court remains the authoritative source.</p><Button href={links.civilOnline} {...external}>Open Civil Online <ExternalLink size={17}/></Button></Step>
    </div>

    <MoneyTypes/><FAQ/>
    <GlassCard className="mt-12" title="Important information"><p>This page provides general information and signposts owners to publicly available resources. It does not constitute legal advice.</p><p>James Square, the James Square Owners Committee and its committee members are not acting as legal representatives and cannot make a claim on behalf of an individual owner.</p><p>Owners remain responsible for checking the current Scottish Courts and Tribunals Service guidance and deciding what action, if any, they wish to take.</p><a className="inline-flex items-center gap-2 font-semibold text-blue-700 hover:underline dark:text-blue-300" href={links.guidance} {...external}>Official Simple Procedure information <ExternalLink size={16}/><span className="sr-only"> (opens in a new tab)</span></a></GlassCard>

    <SimpleModal open={modal==="letter"} onClose={()=>setModal(null)} title="Repayment letter generator"><p className="leading-relaxed text-slate-700 dark:text-slate-200">We’re preparing a tool that will help owners create a repayment request using their own details. Until this is available, you can use the information above to prepare your own written request.</p></SimpleModal>
    <SimpleModal open={modal==="email"} onClose={()=>setModal(null)} title="Follow-up email template"><p className="mb-4 text-sm font-medium text-slate-700 dark:text-slate-200">This is a suggested template only. Check and amend it so that it accurately reflects your own circumstances before sending it.</p><label htmlFor="email-template" className="sr-only">Editable follow-up email template</label><textarea id="email-template" value={email} onChange={e=>setEmail(e.target.value)} rows={14} className="w-full rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm leading-relaxed text-slate-900 dark:border-white/10 dark:bg-slate-950 dark:text-white"/><Button className="mt-4" onClick={copy}><Clipboard size={17}/>{copied ? "Copied" : "Copy template"}</Button><span className="sr-only" aria-live="polite">{copied ? "Copied" : ""}</span></SimpleModal>
  </>;
}

function Step({id,number,title,intro,children}:{id:string;number:string;title:string;intro:string;children:React.ReactNode}) { return <GlassCard as="section" className="scroll-mt-24" contentClassName="space-y-5 text-slate-700 dark:text-slate-200" title={<span id={`${id}-title`} className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-blue-600 text-sm text-white">{number}</span>{title}</span>}><p className="max-w-3xl text-base leading-relaxed">{intro}</p>{children}</GlassCard> }
function Evidence(){const items=["Keep a copy of your repayment letter","Keep your follow-up email","Keep proof of postage or delivery where available","Keep bank statements showing the relevant payments","Keep invoices or payment requests","Keep correspondence received from FIOR","Record any repayment received"];return <fieldset className={panel}><legend className="px-1 font-semibold text-slate-900 dark:text-white">Keep your evidence together</legend><div className="mt-3 grid gap-3 sm:grid-cols-2">{items.map(x=><label key={x} className="flex cursor-pointer items-start gap-3 text-sm"><input type="checkbox" className="mt-0.5 size-4 accent-blue-600"/>{x}</label>)}</div><p className="mt-4 text-xs text-slate-500 dark:text-slate-400">Your selections stay in this browser session and are not saved to James Square.</p></fieldset>}
function Outcomes(){return <div className="grid gap-3 md:grid-cols-3">{[["Payment received","Matter resolved","Keep a record of the payment and your correspondence.","border-emerald-300 bg-emerald-50/60 dark:bg-emerald-400/10"],["FIOR responds or disputes the amount","Response received","Consider the response alongside your own records and supporting evidence.","border-amber-300 bg-amber-50/60 dark:bg-amber-400/10"],["No payment or resolution","Unresolved","You may wish to consider the official Simple Procedure guidance.","border-blue-300 bg-blue-50/60 dark:bg-blue-400/10"]].map(([title,label,copy,style])=><div className={`rounded-2xl border p-4 ${style}`} key={title}><span className="text-xs font-bold uppercase tracking-wider">{label}</span><h3 className="mt-2 font-semibold text-slate-950 dark:text-white">{title}</h3><p className="mt-2 text-sm">{copy}</p></div>)}</div>}
function Resources(){const list=[[FileText,"Simple Procedure guidance","Overview of the procedure and current guidance",links.guidance],[Scale,"Making a claim","Official steps for starting a claim",links.makingAClaim],[Landmark,"Civil Online","The official online civil claims service",links.civilOnline],[FileCheck2,"Simple Procedure forms","Current official forms",links.forms],[Banknote,"Current court fees","Check current fees and exemptions",links.fees],[ArrowRight,"What happens after a claim is submitted","Official information about the next stages",links.afterSubmission]] as const;return <div className="rounded-3xl bg-slate-950 p-5 text-white sm:p-7"><h3 className="text-xl font-semibold">Official Scottish Courts resources</h3><p className="mt-2 text-sm text-slate-300">For court procedure, forms, fees and current guidance, use the official Scottish Courts and Tribunals Service information.</p><div className="mt-5 grid gap-2 sm:grid-cols-2">{list.map(([Icon,title,copy,url])=><a key={title} href={url} {...external} className="group flex gap-3 rounded-xl border border-white/10 bg-white/5 p-4 hover:bg-white/10"><Icon className="shrink-0 text-blue-300" size={20}/><span><strong className="flex items-center gap-2 text-sm">{title}<ExternalLink className="transition-transform group-hover:translate-x-0.5" size={14}/></strong><span className="mt-1 block text-xs text-slate-300">{copy}. Official resource; opens in a new tab.</span></span></a>)}</div><div className="mt-5 flex flex-col gap-3 sm:flex-row"><Button href={links.guidance} {...external}>Start with the official guidance <ExternalLink size={16}/></Button><Button href={links.civilOnline} {...external} variant="secondary">Open Civil Online <ExternalLink size={16}/></Button></div></div>}

function MoneyTypes(){return <section className="mt-16 border-t border-slate-300 pt-14 dark:border-white/15" aria-labelledby="money-title"><h2 id="money-title" className="text-3xl font-semibold text-slate-950 dark:text-white">Is this the right process for you?</h2><p className="mt-3 max-w-3xl text-slate-600 dark:text-slate-300">Not all money connected with FIOR or James Square should be treated in the same way. Choose the description that best matches the payment you are concerned about.</p><div className="mt-7 grid gap-5 lg:grid-cols-3">
<Type icon={<UserRound/>} title="Personal overpayments"><ul className="list-disc space-y-2 pl-5 text-sm"><li>Direct Debits paid to FIOR after the change of factor</li><li>Duplicate payments</li><li>Other money an individual owner believes FIOR owes directly to them</li></ul><p className="rounded-xl bg-blue-50 p-3 font-semibold text-blue-900 dark:bg-blue-400/10 dark:text-blue-200">The process explained above may be relevant to you.</p><a href="#step-1" className="font-semibold text-blue-700 dark:text-blue-300">View the five-step process ↑</a></Type>
<Type icon={<ShieldCheck/>} title="Roof fund payments"><p>Payments made by owners towards roof works around December 2025 and January 2026 may be relevant to an existing Police Scotland enquiry.</p><p>If you made a relevant payment and have information or documentation you believe may assist the enquiry, you can contact the enquiry officer.</p><div className={panel}><strong>{policeContact.name}</strong><span className="block text-sm">{policeContact.organisation}</span><span className="mt-2 block text-sm text-slate-500 dark:text-slate-400">Contact details will be added here once confirmed.</span></div><p className="text-sm">Please retain bank statements, emails, invoices, payment requests and any other documentation relating to the payment.</p></Type>
<Type icon={<Landmark/>} title="Communal James Square funds"><p>Money belonging collectively to the James Square development is different from money an individual owner believes is personally owed to them.</p><p>Myreside Management is continuing to pursue the transfer or recovery of outstanding communal funds from the previous factor.</p><p className="rounded-xl border-l-4 border-slate-500 bg-slate-100 p-3 font-semibold text-slate-900 dark:bg-white/10 dark:text-white">Individual owners should not use this page to make a personal claim for the whole development’s communal funds.</p></Type>
</div></section>}
function Type({icon,title,children}:{icon:React.ReactNode;title:string;children:React.ReactNode}){return <article className="jqs-glass flex flex-col gap-4 p-5 text-sm leading-relaxed text-slate-700 dark:text-slate-200"><span className="grid size-11 place-items-center rounded-xl bg-blue-100 text-blue-700 dark:bg-blue-400/15 dark:text-blue-300">{icon}</span><h3 className="text-xl font-semibold text-slate-950 dark:text-white">{title}</h3>{children}</article>}
const faqs=[["What is Simple Procedure?",<>It is a Scottish court process for certain civil claims. Read the <Official/>.</>],["How much can I claim?",<>Simple Procedure generally covers claims up to £5,000, subject to current SCTS rules. Check the <Official/>.</>],["Do I need a solicitor?",<>Simple Procedure is designed to be accessible without necessarily instructing a solicitor. You remain free to seek independent advice.</>],["Does James Square make the claim for me?",<>No. Any personal claim is made by the individual owner.</>],["What evidence should I keep?",<>Keep bank statements, Direct Debit records, invoices, emails, letters, proof of postage, payment references and relevant correspondence.</>],["What if FIOR responds?",<>Consider the response alongside your evidence and decide what action, if any, you wish to take. This page cannot assess whether a response is legally valid.</>],["What if I am owed more than £5,000?",<>Simple Procedure may not be appropriate. Check current SCTS guidance or seek independent legal advice.</>],["What if my payment related to the roof fund?",<>Read the roof fund section above and the neutral Police Scotland enquiry information.</>],["What about money owed to James Square collectively?",<>Communal development funds are being dealt with separately and should not be treated as an owner’s personal Simple Procedure claim.</>]];
function Official(){return <a href={links.guidance} {...external} className="font-semibold text-blue-700 underline dark:text-blue-300">official guidance<span className="sr-only"> (opens in a new tab)</span></a>}
function FAQ(){return <section className="mt-16" aria-labelledby="faq-title"><h2 id="faq-title" className="text-3xl font-semibold text-slate-950 dark:text-white">Frequently asked questions</h2><div className="mt-6 divide-y divide-slate-200 overflow-hidden rounded-3xl border border-slate-200 bg-white/60 dark:divide-white/10 dark:border-white/10 dark:bg-white/5">{faqs.map(([q,a])=><details key={q as string} className="group"><summary className="flex min-h-14 cursor-pointer list-none items-center justify-between gap-4 px-5 py-4 font-semibold text-slate-900 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-blue-500 dark:text-white">{q}<ChevronDown className="shrink-0 transition-transform group-open:rotate-180 motion-reduce:transition-none" size={19}/></summary><div className="px-5 pb-5 text-sm leading-relaxed text-slate-600 dark:text-slate-300">{a}</div></details>)}</div></section>}
