'use client';

import { FormEvent, useRef, useState } from 'react';
import { CctvErrors, CctvRequest, validateCctvRequest } from '@/lib/cctvRequest';

const today = () => new Date().toISOString().slice(0, 10);
const initial: CctvRequest = { requestorName:'',email:'',telephone:'',property:'',preferredContact:'email',incidentDate:'',timePrecision:'exact',incidentTime:'',timeFrom:'',timeTo:'',incidentType:'crime',location:'',detailedLocation:'',policeStatus:'not-reported',policeReportDate:'',policeReference:'',officerDetails:'',narrative:'',identifyingDetails:'',signature:'',submissionDate:today(),privacyAcknowledgement:false,policeAcknowledgement:false,website:'' };
const inputClass = 'mt-1 min-h-11 w-full rounded-lg border border-slate-400 bg-white px-3 py-2 text-slate-950 focus:outline focus:outline-2 focus:outline-blue-600';

export default function CctvRequestForm() {
  const [form,setForm] = useState(initial); const [errors,setErrors] = useState<CctvErrors>({});
  const [state,setState] = useState<'idle'|'submitting'|'success'|'error'>('idle');
  const [message,setMessage] = useState(''); const status = useRef<HTMLDivElement>(null);
  const set = <K extends keyof CctvRequest>(key: K, value: CctvRequest[K]) => setForm(old => ({...old,[key]:value}));
  const field = (key:keyof CctvRequest,label:string,type='text',required=true) => <label className="block font-medium">{label}{required && <span aria-hidden="true" className="text-red-700"> *</span>}<input className={inputClass} type={type} value={form[key] as string} onChange={e=>set(key,e.target.value as never)} required={required} aria-invalid={!!errors[key]} aria-describedby={errors[key]?`${key}-error`:undefined}/>{errors[key]&&<span id={`${key}-error`} className="mt-1 block text-sm text-red-700">{errors[key]}</span>}</label>;
  const select = (key:keyof CctvRequest,label:string,options:[string,string][]) => <label className="block font-medium">{label} <span aria-hidden="true" className="text-red-700">*</span><select className={inputClass} value={form[key] as string} onChange={e=>set(key,e.target.value as never)}>{options.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select>{errors[key]&&<span className="text-sm text-red-700">{errors[key]}</span>}</label>;
  async function submit(event:FormEvent) {
    event.preventDefault(); if(state==='submitting') return;
    const checked=validateCctvRequest(form); if(!checked.success){setErrors(checked.errors);setState('error');setMessage('Please correct the highlighted fields.');queueMicrotask(()=>status.current?.focus());return;}
    setErrors({});setState('submitting');setMessage('Submitting your request…');
    try { const res=await fetch('/api/cctv/request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(checked.data)}); const body=await res.json(); if(!res.ok) throw new Error(body.error); setState('success');setMessage(`Request submitted successfully. Your request ID is ${body.requestId}. Contact Police Scotland separately if you believe a crime occurred.`);setForm({...initial,submissionDate:today()}); }
    catch(error){setState('error');setMessage(error instanceof Error ? error.message : 'We could not submit your request. Please try again. Your entries have been preserved.');}
    finally { queueMicrotask(()=>status.current?.focus()); }
  }
  return <form onSubmit={submit} noValidate className="mt-8 space-y-8">
    <p className="text-sm"><span className="text-red-700">*</span> Required field</p>
    <fieldset className="grid gap-5 sm:grid-cols-2"><legend className="mb-4 text-xl font-bold">Your details</legend>{field('requestorName','Requestor name')}{field('email','Email','email')}{field('telephone','Telephone','tel')}{field('property','James Square property / flat')}{select('preferredContact','Preferred contact method',[['email','Email'],['telephone','Telephone']])}</fieldset>
    <fieldset className="grid gap-5 sm:grid-cols-2"><legend className="mb-4 text-xl font-bold">Incident details</legend>{field('incidentDate','Incident date','date')}{select('timePrecision','Time is',[['exact','Exact'],['approximate','Approximate'],['window','A time window']])}{form.timePrecision==='window'?<>{field('timeFrom','From','time')}{field('timeTo','To','time')}</>:field('incidentTime',form.timePrecision==='exact'?'Exact time':'Approximate time','time')}{select('incidentType','Incident type',[['crime','Suspected crime'],['antisocial-behaviour','Antisocial behaviour'],['vehicle','Vehicle'],['delivery-package','Delivery / package'],['accident','Accident'],['other','Other']])}{field('location','Location')}{field('detailedLocation','Detailed location')}
      <label className="block font-medium sm:col-span-2">Incident narrative <span className="text-red-700">*</span><textarea className={inputClass} rows={6} value={form.narrative} onChange={e=>set('narrative',e.target.value)} aria-invalid={!!errors.narrative}/>{errors.narrative&&<span className="text-sm text-red-700">{errors.narrative}</span>}</label>
      {(form.incidentType==='vehicle'||form.incidentType==='delivery-package'||form.incidentType==='crime')&&<label className="block font-medium sm:col-span-2">Identifying details for people, vehicles, deliveries or packages{(form.incidentType==='vehicle'||form.incidentType==='delivery-package')&&<span className="text-red-700"> *</span>}<textarea className={inputClass} rows={4} value={form.identifyingDetails} onChange={e=>set('identifyingDetails',e.target.value)}/>{errors.identifyingDetails&&<span className="text-sm text-red-700">{errors.identifyingDetails}</span>}</label>}</fieldset>
    <fieldset className="grid gap-5 sm:grid-cols-2"><legend className="mb-4 text-xl font-bold">Police Scotland report</legend>{select('policeStatus','Reporting status',[['not-reported','Not reported'],['reported','Reported'],['not-applicable','Not applicable']])}{form.policeStatus==='reported'&&<>{field('policeReportDate','Report date','date')}{field('policeReference','Reference number')}{field('officerDetails','Officer / station details')}</>}</fieldset>
    <fieldset className="grid gap-5 sm:grid-cols-2"><legend className="mb-4 text-xl font-bold">Confirmation</legend>{field('signature','Typed signature / full name')}{field('submissionDate','Submission date','date')}<label className="flex gap-3 sm:col-span-2"><input type="checkbox" className="size-5 shrink-0" checked={form.privacyAcknowledgement} onChange={e=>set('privacyAcknowledgement',e.target.checked)}/><span>I acknowledge that my personal information will be used to assess this CCTV request. <span className="text-red-700">*</span>{errors.privacyAcknowledgement&&<span className="block text-sm text-red-700">{errors.privacyAcknowledgement}</span>}</span></label><label className="flex gap-3 sm:col-span-2"><input type="checkbox" className="size-5 shrink-0" checked={form.policeAcknowledgement} onChange={e=>set('policeAcknowledgement',e.target.checked)}/><span>I understand that submitting this form does not report a crime to Police Scotland. <span className="text-red-700">*</span>{errors.policeAcknowledgement&&<span className="block text-sm text-red-700">{errors.policeAcknowledgement}</span>}</span></label></fieldset>
    <label className="absolute -left-[10000px]" aria-hidden="true">Website<input tabIndex={-1} autoComplete="off" value={form.website} onChange={e=>set('website',e.target.value)}/></label>
    <button disabled={state==='submitting'} className="min-h-12 rounded-lg bg-blue-700 px-6 py-3 font-bold text-white disabled:cursor-wait disabled:opacity-60">{state==='submitting'?'Submitting…':'Submit CCTV review request'}</button>
    <div ref={status} tabIndex={-1} role={state==='error'?'alert':'status'} aria-live="polite" className={message?'rounded-lg border p-4 font-medium':''}>{message}</div>
  </form>;
}
