'use client';

import Image from 'next/image';
import { useMemo, useState } from 'react';
import { AlertTriangle, Bath, Briefcase, Car, Check, ChevronDown, ChefHat, Clock, Coffee, Copy, Heart, Home, KeyRound, Leaf, Mail, MapPin, Menu, MessageCircle, Moon, Phone, Shield, ShoppingBag, Sparkles, Train, Tv, Users, Utensils, Waves, Wifi } from 'lucide-react';
import { guestGuide } from '../data/guestGuide';
import type { GuestIcon, GuideItem, LocalRecommendation } from '../types/guestGuide';

const iconMap: Record<GuestIcon, React.ComponentType<{ className?: string }>> = {
  wifi: Wifi, key: KeyRound, car: Car, waves: Waves, home: Home, map: MapPin, phone: Phone, checkout: Check,
  clock: Clock, users: Users, moon: Moon, shield: Shield, train: Train, utensils: Utensils, shopping: ShoppingBag,
  camera: MapPin, coffee: Coffee, thermometer: Bath, tv: Tv, chef: ChefHat, sparkles: Sparkles, trash: AlertTriangle,
  briefcase: Briefcase, leaf: Leaf, alert: AlertTriangle, message: MessageCircle, ambulance: AlertTriangle, heart: Heart,
};

function Icon({ name, className }: { name: GuestIcon; className?: string }) { const C = iconMap[name]; return <C className={className} />; }
function scrollToId(id: string) { document.getElementById(id)?.scrollIntoView({ behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth', block: 'start' }); }

export default function GuestGuidePage() {
  const [menuOpen, setMenuOpen] = useState(false);
  const quick = [
    ['wifi','Wi‑Fi','Network and password','wifi'], ['key','Check-in','Arrival steps','arrival'], ['car','Parking','Bay and access placeholders','transport'], ['waves','Hot tub','Private garden guide','hot-tub'],
    ['home','Apartment guide','Appliances and essentials','apartment'], ['map','Local area','Food, transport and essentials','local'], ['phone','Contact host','Support options','help'], ['checkout','Checkout','Leaving checklist','checkout'],
  ] as const;

  return <div className="min-h-screen overflow-x-hidden bg-[#f7f3ec] text-stone-950 selection:bg-stone-900 selection:text-white">
    <header className="fixed inset-x-0 top-0 z-50 px-3 py-3 sm:px-6">
      <div className="mx-auto flex max-w-6xl items-center justify-between rounded-full border border-white/50 bg-white/75 px-4 py-3 shadow-[0_12px_40px_rgba(42,31,21,.12)] backdrop-blur-xl">
        <button onClick={() => scrollToId('top')} className="font-serif text-lg font-semibold tracking-tight focus:outline-none focus:ring-2 focus:ring-stone-900 rounded-full">James Square Guest Guide</button>
        <nav className="hidden items-center gap-2 md:flex" aria-label="Guest guide sections">
          {['stay','wifi','arrival','hot-tub','local','help'].map((id) => <button key={id} onClick={() => scrollToId(id)} className="rounded-full px-3 py-2 text-sm text-stone-700 hover:bg-stone-900 hover:text-white focus:outline-none focus:ring-2 focus:ring-stone-900 capitalize">{id.replace('-', ' ')}</button>)}
        </nav>
        <div className="flex items-center gap-2"><button onClick={() => scrollToId('help')} className="rounded-full bg-stone-950 px-4 py-2 text-sm font-medium text-white shadow-lg transition active:scale-95">Need help?</button><button onClick={() => setMenuOpen(v => !v)} className="rounded-full border border-stone-200 p-2 md:hidden" aria-label="Open guest menu"><Menu className="h-5 w-5" /></button></div>
      </div>
      {menuOpen && <div className="mx-auto mt-2 max-w-6xl rounded-3xl border border-white/60 bg-white/90 p-3 shadow-xl backdrop-blur-xl md:hidden">{quick.map(([icon,title,,id]) => <button key={id} onClick={() => {setMenuOpen(false); scrollToId(id)}} className="flex w-full items-center gap-3 rounded-2xl p-3 text-left hover:bg-stone-100"><Icon name={icon} className="h-5 w-5" />{title}</button>)}</div>}
    </header>

    <main id="top">
      <section className="relative min-h-[92vh] px-4 pb-12 pt-28 sm:px-6">
        <div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_top_left,rgba(255,255,255,.95),transparent_35%),linear-gradient(135deg,#f7f3ec,#d8c8b7)]" />
        <div className="mx-auto grid max-w-6xl items-center gap-8 lg:grid-cols-[.95fr_1.05fr]">
          <div className="space-y-7"><p className="inline-flex rounded-full border border-stone-300/70 bg-white/55 px-4 py-2 text-sm font-medium text-stone-700 backdrop-blur">{guestGuide.property.locationLine}</p><h1 className="font-serif text-5xl font-semibold leading-[.95] tracking-tight sm:text-7xl">{guestGuide.property.heading}</h1><p className="max-w-xl text-lg leading-8 text-stone-700">{guestGuide.property.intro}</p><div className="flex flex-col gap-3 sm:flex-row"><button onClick={() => scrollToId('quick-actions')} className="rounded-full bg-stone-950 px-6 py-4 font-semibold text-white shadow-xl transition hover:-translate-y-0.5 active:scale-95">Start your stay</button><button onClick={() => scrollToId('help')} className="rounded-full border border-stone-300 bg-white/60 px-6 py-4 font-semibold text-stone-900 backdrop-blur transition hover:bg-white active:scale-95">Need help?</button></div></div>
          <div className="relative aspect-[4/3] overflow-hidden rounded-[2.5rem] border border-white/50 bg-stone-200 shadow-[0_30px_80px_rgba(51,37,23,.25)]"><Image src={guestGuide.property.heroImage || '/images/home-photos/09-building61.png'} alt="James Square apartment building exterior" fill priority sizes="(min-width: 1024px) 50vw, 100vw" className="object-cover" /><div className="absolute inset-x-6 bottom-6 rounded-3xl bg-white/75 p-4 backdrop-blur-xl"><p className="text-sm font-medium text-stone-600">Your apartment</p><p className="font-semibold">{guestGuide.property.address}</p></div></div>
        </div>
      </section>

      <Section id="quick-actions" eyebrow="Essentials" title="Everything guests usually need first"><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{quick.map(([icon,title,label,id]) => <button key={id} onClick={() => scrollToId(id)} className="group min-h-32 rounded-3xl border border-white/70 bg-white/65 p-4 text-left shadow-sm backdrop-blur transition hover:-translate-y-1 hover:shadow-xl active:scale-[.98]"><Icon name={icon} className="mb-4 h-7 w-7 text-stone-800" /><h3 className="font-semibold">{title}</h3><p className="mt-1 text-sm text-stone-600">{label}</p></button>)}</div></Section>
      <Section id="stay" eyebrow="Your stay" title="At a glance"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{guestGuide.stay.map(i => <Card key={i.label}><Icon name={i.icon} className="h-5 w-5"/><p className="mt-4 text-sm text-stone-500">{i.label}</p><p className="font-semibold">{i.value}</p></Card>)}</div></Section>
      <Section id="wifi" eyebrow="Wi‑Fi" title="Connect when details are confirmed"><Card><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm text-stone-500">Network</p><p className="text-2xl font-semibold">{guestGuide.wifi.networkName || 'TODO: Wi‑Fi network name'}</p><p className="mt-3 text-sm text-stone-500">Password</p><p className="font-mono text-lg">{guestGuide.wifi.password || 'TODO: Wi‑Fi password'}</p></div><button onClick={() => guestGuide.wifi.password && navigator.clipboard.writeText(guestGuide.wifi.password)} disabled={!guestGuide.wifi.password} className="inline-flex items-center justify-center gap-2 rounded-full bg-stone-950 px-5 py-3 text-white disabled:cursor-not-allowed disabled:bg-stone-400"><Copy className="h-4 w-4"/>Copy password</button></div><div className="mt-5 rounded-2xl border border-dashed border-stone-300 p-6 text-center text-sm text-stone-500">Optional QR code placeholder</div></Card></Section>
      <Section id="arrival" eyebrow="Arrival" title="Simple check-in sequence"><div className="grid gap-4 md:grid-cols-2">{guestGuide.arrival.map((s,idx) => <Card key={s.title}><div className="flex gap-4"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-stone-950 text-white">{idx+1}</span><div><h3 className="font-semibold">{s.title}</h3><p className="mt-2 text-stone-600">{s.body}</p></div></div></Card>)}</div></Section>
      <Section id="hot-tub" eyebrow="Private outdoor space" title={guestGuide.hotTub.title}><div className="grid gap-5 lg:grid-cols-2"><div className="relative min-h-80 overflow-hidden rounded-[2rem]"><Image src={guestGuide.hotTub.image || '/images/buildingimages/garden.jpg'} alt="Garden placeholder for the private hot tub area" fill sizes="(min-width:1024px) 50vw, 100vw" className="object-cover" /></div><div className="space-y-3"><p className="text-stone-700">{guestGuide.hotTub.description}</p>{guestGuide.hotTub.instructions.map(i => <Accordion key={i.title} item={i}/>)}</div></div></Section>
      <Section id="apartment" eyebrow="Apartment guide" title="Appliances and home essentials"><div className="grid gap-3 md:grid-cols-2">{guestGuide.apartmentGuide.map(i => <Accordion key={i.title} item={i}/>)}</div></Section>
      <Section id="facilities" eyebrow="Shared building facilities" title={guestGuide.facilities.title}><div className="rounded-3xl border border-amber-200 bg-amber-50 p-6 text-amber-950"><p>{guestGuide.facilities.body}</p><div className="mt-4 grid gap-3 sm:grid-cols-3">{guestGuide.facilities.items.map(i => <div key={i.label} className="rounded-2xl bg-white/70 p-4"><Icon name={i.icon} className="h-5 w-5"/><p className="mt-2 font-semibold">{i.label}</p><p className="text-sm">{i.value}</p></div>)}</div></div></Section>
      <LocalSection />
      <Section id="transport" eyebrow="Getting around" title="Transport and parking"><div className="grid gap-3 md:grid-cols-2">{guestGuide.transport.map(i => <Accordion key={i.title} item={i}/>)}</div></Section>
      <Section id="rules" eyebrow="House rules" title="A few things to help everyone enjoy their stay"><div className="grid gap-3">{guestGuide.houseRules.map(i => <Accordion key={i.title} item={i}/>)}</div></Section>
      <Checkout />
      <Help />
    </main>
    <footer className="px-4 py-10"><div className="mx-auto flex max-w-6xl flex-col gap-4 rounded-[2rem] bg-stone-950 p-6 text-white sm:flex-row sm:items-center sm:justify-between"><div><p className="font-serif text-xl">James Square Guest Guide</p><p className="text-sm text-white/70">Edinburgh · Private guest information</p></div><button onClick={() => scrollToId('top')} className="rounded-full bg-white px-4 py-2 text-stone-950">Return to top</button></div></footer>
  </div>;
}

function Section({ id, eyebrow, title, children }: { id: string; eyebrow: string; title: string; children: React.ReactNode }) { return <section id={id} className="scroll-mt-28 px-4 py-12 sm:px-6"><div className="mx-auto max-w-6xl"><p className="mb-3 text-sm font-semibold uppercase tracking-[.22em] text-stone-500">{eyebrow}</p><h2 className="mb-6 font-serif text-3xl font-semibold sm:text-5xl">{title}</h2>{children}</div></section>; }
function Card({ children }: { children: React.ReactNode }) { return <div className="rounded-3xl border border-white/70 bg-white/70 p-5 shadow-sm backdrop-blur">{children}</div>; }
function Accordion({ item }: { item: GuideItem }) { const [open,setOpen]=useState(false); return <div className="rounded-3xl border border-white/70 bg-white/70 p-4 shadow-sm backdrop-blur"><button onClick={()=>setOpen(!open)} className="flex w-full items-center justify-between gap-3 text-left"><span className="flex items-center gap-3"><Icon name={item.icon} className="h-5 w-5"/><span><strong>{item.title}</strong><span className="block text-sm text-stone-600">{item.summary}</span></span></span><ChevronDown className={`h-5 w-5 transition ${open?'rotate-180':''}`}/></button>{open && <div className="mt-4 space-y-2 border-t border-stone-200 pt-4 text-stone-700">{item.instructions.map(x=><p key={x}>{x}</p>)}{item.videoUrl && <a href={item.videoUrl} target="_blank" rel="noopener noreferrer" className="underline">Watch guide</a>}</div>}</div>; }
function LocalSection(){ const [cat,setCat]=useState('Food and drink'); const recs=useMemo(()=>guestGuide.localRecommendations.filter(r=>r.category===cat),[cat]); return <Section id="local" eyebrow="Local area" title="Edinburgh on your doorstep"><div className="mb-5 flex gap-2 overflow-x-auto pb-2">{guestGuide.localCategories.map(c=><button key={c} onClick={()=>setCat(c)} className={`shrink-0 rounded-full px-4 py-2 text-sm ${cat===c?'bg-stone-950 text-white':'bg-white/70 text-stone-700'}`}>{c}</button>)}</div><div className="grid gap-3 md:grid-cols-3">{(recs.length?recs:guestGuide.localRecommendations.slice(0,3)).map((r:LocalRecommendation)=><Card key={r.name}><p className="text-sm text-stone-500">{r.category}{r.hostPick?' · Host pick':''}</p><h3 className="mt-2 text-xl font-semibold">{r.name}</h3><p className="mt-2 text-stone-600">{r.description}</p>{r.walkingTime && <p className="mt-3 text-sm font-medium">Walk: {r.walkingTime}</p>}{r.mapUrl && <a href={r.mapUrl} target="_blank" rel="noopener noreferrer" className="mt-4 inline-flex rounded-full bg-stone-100 px-4 py-2 text-sm font-medium">Open map</a>}</Card>)}</div></Section> }
function Checkout(){ const [done,setDone]=useState<string[]>([]); return <Section id="checkout" eyebrow="Checkout" title="A calm leaving checklist"><div className="grid gap-3 md:grid-cols-2">{guestGuide.checkout.map(i=><button key={i} onClick={()=>setDone(d=>d.includes(i)?d.filter(x=>x!==i):[...d,i])} className="flex items-center gap-3 rounded-3xl bg-white/70 p-4 text-left shadow-sm"><span className={`flex h-7 w-7 items-center justify-center rounded-full border ${done.includes(i)?'bg-stone-950 text-white':'border-stone-300'}`}>{done.includes(i)&&<Check className="h-4 w-4"/>}</span>{i}</button>)}</div></Section> }
function Help(){ const c=guestGuide.contacts; return <Section id="help" eyebrow="Need help" title="Support during your stay"><div className="grid gap-3 md:grid-cols-3"><Card><AlertTriangle className="h-6 w-6"/><h3 className="mt-3 font-semibold">Urgent emergency</h3><p className="mt-2 text-stone-600">For police, fire or ambulance emergencies in the UK, call 999.</p><a href="tel:999" className="mt-4 inline-flex rounded-full bg-red-700 px-4 py-2 text-white">Call 999</a></Card>{([[Phone,'Call host',c.hostPhone],[MessageCircle,'WhatsApp host',c.whatsapp],[Mail,'Message host',c.email]] as const).map(([ContactIcon,label,value])=><Card key={label}><ContactIcon className="h-6 w-6"/><h3 className="mt-3 font-semibold">{label}</h3><p className="mt-2 text-stone-600">{value || 'TODO: contact detail to be supplied'}</p></Card>)}</div></Section> }
